### ISSUE TITLE
LCD - 'LCDController' object has no attribute 'LCD_CMD'

### ISSUE THREAD

**Issue by mrplow** [kizniche/Mycodo#514]
## Mycodo Issue Report:
  - Specific Mycodo Version: 6.2.0
 
#### Problem Description
My LCD isn't working since the update to 6.2.0. I've deleted and recreated the LCD object but I see the following error in the daemon log once I activate it.
 
### Errors
```2018-08-17 20:10:40,476 - mycodo.lcd_30e0a718 - INFO - Activated in 710.4 ms
2018-08-17 20:10:41,477 - mycodo.lcd_30e0a718 - ERROR - Could not initialize LCD. Check your configuration and wiring. Error: 'LCDController' object has no attribute 'LCD_CMD'
2018-08-17 20:10:52,514 - mycodo.daemon - ERROR - Could not flash LCD: 'LCDController' object has no attribute 'LCD_CMD'
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 608, in lcd_flash
    return self.controller['LCD'][lcd_id].lcd_flash(state)
  File "/var/mycodo-root/mycodo/controller_lcd.py", line 461, in lcd_flash
    self.lcd_backlight(True)
  File "/var/mycodo-root/mycodo/controller_lcd.py", line 468, in lcd_backlight
    self.lcd_byte(0x01, self.LCD_CMD, self.LCD_BACKLIGHT)
AttributeError: 'LCDController' object has no attribute 'LCD_CMD'
2018-08-17 20:12:55,437 - mycodo.lcd_30e0a718 - ERROR - Error: 'unit'
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controller_lcd.py", line 172, in __init__
    each_lcd_display.line_4_measurement)
  File "/var/mycodo-root/mycodo/controller_lcd.py", line 433, in setup_lcd_line
    self.lcd_line[display_id][line]['unit'] = self.list_inputs[measurement]['unit']
KeyError: 'unit'
```

**Comment by kizniche** [comment]
I have no idea how the lcd_flash error is happening. I just pushed a fix for the unit error. I'll investigate it more.

**Comment by kizniche** [comment]
Could you send me your mycodo database (~/Mycodo/databases/mycodo.db) to investigate further? I haven't been able to replicate your issue... My LCD is working fine. You can contact me at http://kylegabriel.com/contact/ if you don't already have my email. I'll reply with my email if you don't.

**Comment by mrplow** [comment]
@kizniche
No problem, email sent via website form. Once I get your email I'll send you the db file.

Does the daemon need to be stopped first before copying?

Thanks a bunch

**Comment by mrplow** [comment]
Hey @kizniche 6.2.1 solved this issue

**Comment by kizniche** [comment]
Thanks for the help.
