### ISSUE TITLE
TypeError: check_triggers() got an unexpected keyword argument 'state')

### ISSUE THREAD

**Issue by 0x0f906** [kizniche/Mycodo#632]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.2.4
 
#### Problem Description
Please list: After upgrade to 7.2.4 new error pops up in my logs. Not sure it's having an actual affect but thought I'd let you know. 
 
### Errors
2019-02-21 20:22:07,473 - mycodo.daemon - ERROR - Could not turn output on: check_triggers() got an unexpected keyword argument 'state'
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 920, in output_on
    trigger_conditionals=trigger_conditionals)
  File "/var/mycodo-root/mycodo/controller_output.py", line 556, in output_on_off
    duty_cycle=duty_cycle)
TypeError: check_triggers() got an unexpected keyword argument 'state')

### Additional Notes
Aside from that all is well with 7.2.4 thanks for fixing the 20x4 LCD! Made my day to see that drop.

**Comment by kizniche** [comment]
Thanks for the bug report. This was fixed with commit 6cba13f and will be in the 7.3.0 release.
